### ISSUE TITLE
Handle multiline logs

### ISSUE THREAD

**Issue by tsn77130** [fabric8io/docker-fluentd-kubernetes#11]
Hi all,

Is there a way to handle multiline logs from pods ?

Actually are parsed in JSON single line format, but with logs like below it is not very readable

> {"log":"FROM error.orphan) AS anon_1 ON anon_1.id_orphan = error.orphan.id_orphan \n","stream":"stderr","time":"2016-07-27T13:33:22.104446472Z"}
> {"log":"WHERE error.orphan.treated = false AND anon_1.row_number = %(row_number_1)s ORDER BY anon_1.count_messages DESC \n","stream":"stderr","time":"2016-07-27T13:33:22.10454599Z"}
> {"log":" LIMIT %(param_1)s OFFSET %(param_2)s\n","stream":"stderr","time":"2016-07-27T13:33:22.104718326Z"}
> {"log":"2016-07-27 15:33:22,102 INFO  [tools:sqlalchemy.engine.base.Engine] {'param_1': 25, 'row_number_1': 1, 'param_2': 0}\n","stream":"stderr","time":"2016-07-27T13:33:22.104757851Z"}

**Comment by tsn77130** [comment]
fluent-plugin-concat is the solution

**Comment by jimmidyson** [comment]
@tsn77130 Would love to hear what you do with that - care to share?

**Comment by tsn77130** [comment]
Yeah, I use this plugin to regroup multilines (with multiline_start_regexp parameter) from my JSON docker logs on kubernetes (with ES /Fluentd / Kibana associated ), an then I parse them with fluent-plugin-parser , so I can handle correctly traceback and other multilines logs in elasticsearch.
