### ISSUE TITLE
start-fluentd script

### ISSUE THREAD

**Issue by jchauncey** [fabric8io/docker-fluentd-kubernetes#2]
What's the purpose of this script? I cant find where its being called but it looks like it should be used.

**Comment by jimmidyson** [comment]
That should be the entrypoint. I'd totally forgotten about it. Oops. I'll fix that up when I get a chance. The only reason for it is to tune the logging a bit, but the defaults should be good enough in most cases.

**Comment by jchauncey** [comment]
Ah k I'm forking this and adding a syslog plugin so I can try sending logs
to papertrail too.

**Comment by jimmidyson** [comment]
Sounds good. If we can turn this into a helm or deployment manager package then we can make it configurable somehow (I've no experience with either of them yet...).

**Comment by jchauncey** [comment]
Yeah I've got a helm package for elastic search and kibana. Waiting for
support for daemonsets. But all we will need to do is drop in the manifest.

**Comment by jimmidyson** [comment]
Switched back to `start-fluentd` for more configurable fluentd buffers.
