### ISSUE TITLE
fluent-plugin-elasticsearch should be upgraded to avoid Content-Type deprecation warnings

### ISSUE THREAD

**Issue by cbonte** [fabric8io/docker-fluentd-kubernetes#26]
With Elasticsearch >= 5.3, REST requests without a Content-Type will generate a warning log :

```
Content type detection for rest requests is deprecated
```
This has been fixed in fluent-plugin-elasticsearch 1.9.4 via https://github.com/uken/fluent-plugin-elasticsearch/pull/250
Is it possible to bump the version at least to this one ? The current latest version is 1.9.5.

**Comment by jimmidyson** [comment]
Sounds good to me. Would you be able to send in a PR?

**Comment by cbonte** [comment]
Sure ! work in progress.

**Comment by jimmidyson** [comment]
Awesome thanks @cbonte!

**Comment by cbonte** [comment]
PR #27 is available.

**Comment by cbonte** [comment]
Hi @jimmidyson ! Is it possible to merge the PR ? Also, is it possible to plan a new release ?
Thanks.

**Comment by jimmidyson** [comment]
Done @cbonte! v1.21 should be available on Docker Hub soon.

**Comment by cbonte** [comment]
Upgraded with the 1.21 image, everything looks OK. I close the issue ;-)

**Comment by jimmidyson** [comment]
Thanks!
